### ISSUE TITLE
Wrong request type for password-protected blogs

### ISSUE THREAD

**Issue by f055** [damog/www-tumblr#11] opened 2014-09-10 23:44 UTC
Tumblr API v2 when operating on a password-protected blog will not return anything if the API call is authenticated via the "apikey" only. To make request like "info", "likes" or "posts", one needs to use the "oauth" api_method. Maybe it would be good to turn all ::Blog api_methods to use oauth, instead of leaving some to use the simpler apikey? Not sure if detecting password-protected blogs is possible, to adjust accordingly.

**Comment by damog** [comment] 2016-07-17 12:03
Can you please provide an code sample to reproduce?

**Comment by damog** [comment] 2016-08-20 16:35
Closing because I was never able to reproduce. Also, sorry for responding a couple of years later :)

**Closed by damog** 2016-08-20 16:35 UTC
